# Named Entity Recognition using Bert


## Introduction

Named Entity Recognition (NER) is the process of identifying named entities in text.
Example of named entities are: "Person", "Location", "Organization", "Dates" etc. NER is
essentially a token classification task where every token is classified into one or more
predetermined categories.

In this exercise, we will train a simple Transformer based model to perform NER. We will
be using the data from CoNLL 2003 shared task. For more information about the dataset,
please visit [the dataset website](https://www.clips.uantwerpen.be/conll2003/ner/).
However, since obtaining this data requires an additional step of getting a free license, we will be using
HuggingFace's datasets library which contains a processed version of this dataset.

## Install the open source datasets library from HuggingFace

In [1]:
!pip3 install datasets
!wget https://raw.githubusercontent.com/sighsmile/conlleval/master/conlleval.py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
--2023-03-19 12:12:52--  https://raw.githubusercontent.com/sighsmile/conlleval/master/conlleval.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7502 (7.3K) [text/plain]
Saving to: ‘conlleval.py.1’

conlleval.py.1      100%[===================>]   7.33K  --.-KB/s    in 0s      

2023-03-19 12:12:53 (61.1 MB/s) - ‘conlleval.py.1’ saved [7502/7502]



In [2]:
!pip install git+https://github.com/keras-team/keras-nlp.git --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/keras-team/keras-nlp.git to /tmp/pip-req-build-0yemlulk
  Running command git clone --filter=blob:none --quiet https://github.com/keras-team/keras-nlp.git /tmp/pip-req-build-0yemlulk
  Resolved https://github.com/keras-team/keras-nlp.git to commit 1b1781fc195380e529f862c80521a4518f7ec6d3
  Preparing metadata (setup.py) ... done


In [3]:
import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from datasets import load_dataset
from collections import Counter
from conlleval import evaluate

We will be using the transformer implementation from this fantastic
[example](https://keras.io/examples/nlp/text_classification_with_transformer/).

Let's start by defining a `TransformerBlock` layer:

In [41]:

class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super().__init__()
        self.att = keras.layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim
        )
        self.ffn = keras.Sequential(
            [
                keras.layers.Dense(ff_dim, activation="relu"),
                keras.layers.Dense(embed_dim),
            ]
        )
        self.layernorm1 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = keras.layers.Dropout(rate)
        self.dropout2 = keras.layers.Dropout(rate)

    def call(self, inputs, training=False):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)


Next, let's define a `TokenAndPositionEmbedding` layer:

In [42]:

class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim):
        super().__init__()
        self.token_emb = keras.layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = keras.layers.Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, inputs):
        maxlen = tf.shape(inputs)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        position_embeddings = self.pos_emb(positions)
        token_embeddings = self.token_emb(inputs)
        return token_embeddings + position_embeddings


## Build the NER model class as a `keras.Model` subclass

In [43]:

class NERModel(keras.Model):
    def __init__(
        self, num_tags, vocab_size, maxlen=128, embed_dim=32, num_heads=2, ff_dim=32
    ):
        super().__init__()
        self.embedding_layer = TokenAndPositionEmbedding(maxlen, vocab_size, embed_dim)
        self.transformer_block = TransformerBlock(embed_dim, num_heads, ff_dim)
        self.dropout1 = layers.Dropout(0.1)
        self.ff = layers.Dense(ff_dim, activation="relu")
        self.dropout2 = layers.Dropout(0.1)
        self.ff_final = layers.Dense(num_tags, activation="softmax")

    def call(self, inputs, training=False):
        x = self.embedding_layer(inputs)
        x = self.transformer_block(x)
        x = self.dropout1(x, training=training)
        x = self.ff(x)
        x = self.dropout2(x, training=training)
        x = self.ff_final(x)
        return x


## Load the CoNLL 2003 dataset from the datasets library and process it

In [4]:
conll_data = load_dataset("conll2003")

  0%|          | 0/3 [00:00<?, ?it/s]

We will export this data to a tab-separated file format which will be easy to read as a
`tf.data.Dataset` object.

In [6]:

def export_to_file(export_file_path, data):
    with open(export_file_path, "w") as f:
        for record in data:
            ner_tags = record["ner_tags"]
            tokens = record["tokens"]
            if len(tokens) > 0:
                f.write(
                    str(len(tokens))
                    + "\t"
                    + "\t".join(tokens)
                    + "\t"
                    + "\t".join(map(str, ner_tags))
                    + "\n"
                )


# os.mkdir("data")
export_to_file("./data/conll_train.txt", conll_data["train"])
export_to_file("./data/conll_val.txt", conll_data["validation"])

## Make the NER label lookup table

NER labels are usually provided in IOB, IOB2 or IOBES formats. Checkout this link for
more information:
[Wikipedia](https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging))

Note that we start our label numbering from 1 since 0 will be reserved for padding. We
have a total of 10 labels: 9 from the NER dataset and one for padding.

In [7]:

def make_tag_lookup_table():
    iob_labels = ["B", "I"]
    ner_labels = ["PER", "ORG", "LOC", "MISC"]
    all_labels = [(label1, label2) for label2 in ner_labels for label1 in iob_labels]
    all_labels = ["-".join([a, b]) for a, b in all_labels]
    all_labels = ["[PAD]", "O"] + all_labels
    return dict(zip(range(0, len(all_labels) + 1), all_labels))


mapping = make_tag_lookup_table()
print(mapping)

{0: '[PAD]', 1: 'O', 2: 'B-PER', 3: 'I-PER', 4: 'B-ORG', 5: 'I-ORG', 6: 'B-LOC', 7: 'I-LOC', 8: 'B-MISC', 9: 'I-MISC'}


Get a list of all tokens in the training dataset. This will be used to create the
vocabulary.

In [8]:
all_tokens = sum(conll_data["train"]["tokens"], [])
all_tokens_array = np.array(list(map(str.lower, all_tokens)))

counter = Counter(all_tokens_array)
print(len(counter))

num_tags = len(mapping)
vocab_size = 20000

# We only take (vocab_size - 2) most commons words from the training data since
# the `StringLookup` class uses 2 additional tokens - one denoting an unknown
# token and another one denoting a masking token
vocabulary = [token for token, count in counter.most_common(vocab_size - 2)]

# The StringLook class will convert tokens to token IDs
lookup_layer = keras.layers.StringLookup(
    vocabulary=vocabulary
)

print(vocabulary[:10])

21009
['the', '.', ',', 'of', 'in', 'to', 'a', 'and', '(', ')']


Create 2 new `Dataset` objects from the training and validation data

In [10]:
train_data = tf.data.TextLineDataset("./data/conll_train.txt")
val_data = tf.data.TextLineDataset("./data/conll_val.txt")

Print out one line to make sure it looks good. The first record in the line is the number of tokens.
After that we will have all the tokens followed by all the ner tags.

In [11]:
print(list(train_data.take(1).as_numpy_iterator()))

[b'9\tEU\trejects\tGerman\tcall\tto\tboycott\tBritish\tlamb\t.\t3\t0\t7\t0\t0\t0\t7\t0\t0']


We will be using the following map function to transform the data in the dataset:

In [14]:
byte_string_list = [b'9', b'EU', b'rejects', b'German', b'call', b'to', b'boycott', b'British', b'lamb', b'.', b'3', b'0', b'7', b'0', b'0', b'0', b'7', b'0', b'0']

string_list = [x.decode() for x in byte_string_list]

print(string_list)


['9', 'EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.', '3', '0', '7', '0', '0', '0', '7', '0', '0']


In [16]:
import keras_nlp

preprocessor = keras_nlp.models.BertPreprocessor.from_preset(
        "bert_base_en_uncased"
)

record = list(train_data.take(1).as_numpy_iterator())

record = tf.strings.split(record, sep="\t")



output = preprocessor(x = record[0])

for i in train_data:
  record = tf.strings.split(i)
  print(record)
  break


# Convert the tensor to a NumPy array
numpy_array = record.numpy()

# Convert the NumPy array to a Python list
python_list = numpy_array.tolist()


print(python_list)

tf.Tensor(
[b'9' b'EU' b'rejects' b'German' b'call' b'to' b'boycott' b'British'
 b'lamb' b'.' b'3' b'0' b'7' b'0' b'0' b'0' b'7' b'0' b'0'], shape=(19,), dtype=string)
[b'9', b'EU', b'rejects', b'German', b'call', b'to', b'boycott', b'British', b'lamb', b'.', b'3', b'0', b'7', b'0', b'0', b'0', b'7', b'0', b'0']


In [14]:
index = 0
features = []
labels = []

for i in train_data:
  if index > 20:
    break
  record = tf.strings.split(i)
  
  # Convert the tensor to a NumPy array
  numpy_array = record.numpy()

  # Convert the NumPy array to a Python list
  python_list = numpy_array.tolist()

  string_list = [x.decode() for x in python_list]


  length = tf.strings.to_number(record[0], out_type=tf.int32)

  tokens = record[1 : length + 1]

  for i in tokens:
    features.append(i)

  tags = record[length + 1 :]
  tags = tf.strings.to_number(tags, out_type=tf.int64)
  tags += 1

  for j in tags:
    labels.append(j)

  index += 1

print(features[:100])
print(labels[:100])

[<tf.Tensor: shape=(), dtype=string, numpy=b'EU'>, <tf.Tensor: shape=(), dtype=string, numpy=b'rejects'>, <tf.Tensor: shape=(), dtype=string, numpy=b'German'>, <tf.Tensor: shape=(), dtype=string, numpy=b'call'>, <tf.Tensor: shape=(), dtype=string, numpy=b'to'>, <tf.Tensor: shape=(), dtype=string, numpy=b'boycott'>, <tf.Tensor: shape=(), dtype=string, numpy=b'British'>, <tf.Tensor: shape=(), dtype=string, numpy=b'lamb'>, <tf.Tensor: shape=(), dtype=string, numpy=b'.'>, <tf.Tensor: shape=(), dtype=string, numpy=b'Peter'>, <tf.Tensor: shape=(), dtype=string, numpy=b'Blackburn'>, <tf.Tensor: shape=(), dtype=string, numpy=b'BRUSSELS'>, <tf.Tensor: shape=(), dtype=string, numpy=b'1996-08-22'>, <tf.Tensor: shape=(), dtype=string, numpy=b'The'>, <tf.Tensor: shape=(), dtype=string, numpy=b'European'>, <tf.Tensor: shape=(), dtype=string, numpy=b'Commission'>, <tf.Tensor: shape=(), dtype=string, numpy=b'said'>, <tf.Tensor: shape=(), dtype=string, numpy=b'on'>, <tf.Tensor: shape=(), dtype=string, 

{0: '[PAD]', 1: 'O', 2: 'B-PER', 3: 'I-PER', 4: 'B-ORG', 5: 'I-ORG', 6: 'B-LOC', 7: 'I-LOC', 8: 'B-MISC', 9: 'I-MISC'}

In [ ]:
import keras_nlp

classifier = keras_nlp.models.BertClassifier.from_preset(
        "bert_base_en_uncased",
        num_classes=10,
)

classifier.fit(x=features, y=labels, batch_size=2)


 37/240 [===>..........................] - ETA: 49:04 - loss: 1.2647 - sparse_categorical_accuracy: 0.7297

In [91]:
output = classifier.predict(x=['aman'])

print(output)


1/1 [==============================] - 1s 1s/step
[[nan nan nan nan nan nan nan nan nan]]


In [58]:
features = []
labels = []

def map_record_to_training_data(record):
    record = tf.strings.split(record, sep="\t")
    length = tf.strings.to_number(record[0], out_type=tf.int32)
    tokens = record[1 : length + 1]

    tags = record[length + 1 :]
    tags = tf.strings.to_number(tags, out_type=tf.int64)
    tags += 1

    return tokens, tags


def lowercase_and_convert_to_ids(tokens):
    tokens = tf.strings.lower(tokens)
    return lookup_layer(tokens)


# We use `padded_batch` here because each record in the dataset has a
# different length.
batch_size = 32
train_dataset = (
    train_data.map(map_record_to_training_data)
    .map(lambda x, y: (lowercase_and_convert_to_ids(x), y))
    .padded_batch(batch_size)
)
val_dataset = (
    val_data.map(map_record_to_training_data)
    .map(lambda x, y: (lowercase_and_convert_to_ids(x), y))
    .padded_batch(batch_size)
)


ner_model = NERModel(num_tags, vocab_size, embed_dim=32, num_heads=4, ff_dim=64)


Tensor("strided_slice_1:0", shape=(None,), dtype=string)
Tensor("strided_slice_1:0", shape=(None,), dtype=string)


We will be using a custom loss function that will ignore the loss from padded tokens.

In [18]:

class CustomNonPaddingTokenLoss(keras.losses.Loss):
    def __init__(self, name="custom_ner_loss"):
        super().__init__(name=name)

    def call(self, y_true, y_pred):
        loss_fn = keras.losses.SparseCategoricalCrossentropy(
            from_logits=True, reduction=keras.losses.Reduction.NONE
        )
        loss = loss_fn(y_true, y_pred)
        mask = tf.cast((y_true > 0), dtype=tf.float32)
        loss = loss * mask
        return tf.reduce_sum(loss) / tf.reduce_sum(mask)


loss = CustomNonPaddingTokenLoss()

In [19]:
model.compile(optimizer="adam", loss=loss)
model.fit(train_dataset, epochs=10)


def tokenize_and_convert_to_ids(text):
    tokens = text.split()
    return lowercase_and_convert_to_ids(tokens)


# Sample inference using the trained model
sample_input = tokenize_and_convert_to_ids(
    "eu rejects german call to boycott british lamb"
)
sample_input = tf.reshape(sample_input, shape=[1, -1])
print(sample_input)

output = model.predict(sample_input)
prediction = np.argmax(output, axis=-1)[0]
prediction = [mapping[i] for i in prediction]

# eu -> B-ORG, german -> B-MISC, british -> B-MISC
print(prediction)

Epoch 1/10


ValueError: ignored

## Compile and fit the model

In [25]:
ner_model.compile(optimizer="adam", loss=loss)
ner_model.fit(train_dataset, epochs=10)


def tokenize_and_convert_to_ids(text):
    tokens = text.split()
    return lowercase_and_convert_to_ids(tokens)


# Sample inference using the trained model
sample_input = tokenize_and_convert_to_ids(
    "eu rejects german call to boycott british lamb"
)
sample_input = tf.reshape(sample_input, shape=[1, -1])
print(sample_input)

output = ner_model.predict(sample_input)
prediction = np.argmax(output, axis=-1)[0]
prediction = [mapping[i] for i in prediction]

# eu -> B-ORG, german -> B-MISC, british -> B-MISC
print(prediction)

Epoch 1/10


/usr/local/lib/python3.9/dist-packages/keras/backend.py:5585: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


439/439 [==============================] - 66s 129ms/step - loss: 0.6132
Epoch 2/10
439/439 [==============================] - 5s 11ms/step - loss: 0.2479
Epoch 3/10
439/439 [==============================] - 6s 14ms/step - loss: 0.1512
Epoch 4/10
439/439 [==============================] - 5s 11ms/step - loss: 0.1167
Epoch 5/10
439/439 [==============================] - 6s 14ms/step - loss: 0.0956
Epoch 6/10
439/439 [==============================] - 5s 12ms/step - loss: 0.0774
Epoch 7/10
439/439 [==============================] - 6s 14ms/step - loss: 0.0655
Epoch 8/10
439/439 [==============================] - 5s 11ms/step - loss: 0.0591
Epoch 9/10
439/439 [==============================] - 6s 13ms/step - loss: 0.0514
Epoch 10/10
439/439 [==============================] - 5s 11ms/step - loss: 0.0445
tf.Tensor([[  988 10950   204   628     6  3938   215  5773]], shape=(1, 8), dtype=int64)
1/1 [==============================] - 0s 232ms/step
['B-ORG', 'O', 'I-ORG', 'O', 'O', 'O', 'B-MIS

## Metrics calculation

Here is a function to calculate the metrics. The function calculates F1 score for the
overall NER dataset as well as individual scores for each NER tag.

In [ ]:

def calculate_metrics(dataset):
    all_true_tag_ids, all_predicted_tag_ids = [], []

    for x, y in dataset:
        output = ner_model.predict(x)
        predictions = np.argmax(output, axis=-1)
        predictions = np.reshape(predictions, [-1])

        true_tag_ids = np.reshape(y, [-1])

        mask = (true_tag_ids > 0) & (predictions > 0)
        true_tag_ids = true_tag_ids[mask]
        predicted_tag_ids = predictions[mask]

        all_true_tag_ids.append(true_tag_ids)
        all_predicted_tag_ids.append(predicted_tag_ids)

    all_true_tag_ids = np.concatenate(all_true_tag_ids)
    all_predicted_tag_ids = np.concatenate(all_predicted_tag_ids)

    predicted_tags = [mapping[tag] for tag in all_predicted_tag_ids]
    real_tags = [mapping[tag] for tag in all_true_tag_ids]

    evaluate(real_tags, predicted_tags)


calculate_metrics(val_dataset)

## Conclusions

In this exercise, we created a simple transformer based named entity recognition model.
We trained it on the CoNLL 2003 shared task data and got an overall F1 score of around 70%.
State of the art NER models fine-tuned on pretrained models such as BERT or ELECTRA can easily
get much higher F1 score -between 90-95% on this dataset owing to the inherent knowledge
of words as part of the pretraining process and the usage of subword tokenization.

You can use the trained model hosted on [Hugging Face Hub](https://huggingface.co/keras-io/ner-with-transformers) and try the demo on [Hugging Face Spaces](https://huggingface.co/spaces/keras-io/ner_with_transformers).